/**
 * Keywords and environments for TeX language support in CodeMirror.
 * This file defines the keywords, environments, and packages used in TeX documents.
 * It is used to provide syntax highlighting, autocompletion, and linting features.
 *
 * Quick Documentation:
 * - Keywords that are stand alone (e.g. \maketitle) have `hasNested: false`.
 * - Keywords that can have nested options (e.g. \usepackage{...}) have `hasNested: true`
 *   and `nestedOptions` which is an array of valid options for that keyword.
 * - Keywords that have "creative" nested options (e.g. \chapter{...}) have `hasNested: true`
 *   but no `nestedOptions` array, as they can take any text as an argument.
 */

export const texEnvironments = [
  'document',
  'abstract',
  'itemize',
  'enumerate',
  'description',
  'figure',
  'table',
  'equation',
  'align',
  'alignat',
  'gather',
  'multline',
  'split',
  'cases',
  'matrix',
  'pmatrix',
  'bmatrix',
  'vmatrix',
  'Vmatrix',
  'array',
  'tabular',
  'tabbing',
  'verbatim',
  'verse',
  'quotation',
  'quote',
  'center',
  'flushleft',
  'flushright',
  'minipage',
  'theorem',
  'lemma',
  'corollary',
  'proposition',
  'definition',
  'example',
  'remark',
  'proof',
  'thebibliography',
  'titlepage',
  'appendix',
]

export const texPackages = [
  'amsmath',
  'amsfonts',
  'amssymb',
  'graphicx',
  'hyperref',
  'url',
  'xcolor',
  'color',
  'tikz',
  'pgfplots',
  'booktabs',
  'array',
  'longtable',
  'multirow',
  'makecell',
  'geometry',
  'fancyhdr',
  'babel',
  'inputenc',
  'fontenc',
  'lmodern',
  'microtype',
  'setspace',
  'enumitem',
  'listings',
  'algorithm2e',
  'algorithmic',
  'subfig',
  'subcaption',
  'float',
  'wrapfig',
  'caption',
  'natbib',
  'biblatex',
  'csquotes',
  'appendix',
  'tocbibind',
  'nomencl',
  'glossaries',
  'acronym',
  'siunitx',
  'textcomp',
  'gensymb',
  'mhchem',
  'chemfig',
  'pgf',
  'pgffor',
  'calc',
  'xparse',
  'etoolbox',
  'xstring',
  'ifthen',
  'forloop',
]

export interface TexKeyword {
  name: string
  hasNested?: boolean
  nestedOptions?: string[]
}

export const texKeywords: TexKeyword[] = [
  {
    name: 'usepackage',
    hasNested: true,
    nestedOptions: texPackages,
  },
  {
    name: 'begin',
    hasNested: true,
    nestedOptions: texEnvironments,
  },
  {
    name: 'end',
    hasNested: true,
    nestedOptions: texEnvironments,
  },
  {
    name: 'documentclass',
    hasNested: true,
    nestedOptions: ['article', 'report', 'book', 'letter'],
  },
  // TODO: Is it possible to insert an array of uploaded files in filament?
  {
    name: 'graphicspath',
    hasNested: true,
    nestedOptions: [],
  },
  {
    name: 'documentclass',
    hasNested: true,
    nestedOptions: ['article', 'report', 'book', 'letter'],
  },
  { name: 'section', hasNested: true },
  { name: 'subsection', hasNested: true },
  { name: 'subsubsection', hasNested: true },
  { name: 'chapter', hasNested: true },
  { name: 'part', hasNested: true },
  { name: 'title', hasNested: true },
  { name: 'author', hasNested: true },
  { name: 'date', hasNested: true },
  { name: 'maketitle', hasNested: false },
  { name: 'tableofcontents', hasNested: false },
  { name: 'newpage', hasNested: false },
  { name: 'clearpage', hasNested: false },
  { name: 'pagebreak', hasNested: false },
  { name: 'newline', hasNested: false },
  { name: 'linebreak', hasNested: false },
  { name: 'noindent', hasNested: false },
  { name: 'indent', hasNested: false },
  { name: 'textbf', hasNested: true },
  { name: 'textit', hasNested: true },
  { name: 'textsc', hasNested: true },
  { name: 'textsc', hasNested: true },
  { name: 'emph', hasNested: true },
  { name: 'underline', hasNested: true },
  { name: 'cite', hasNested: true },
  { name: 'ref', hasNested: true },
  { name: 'label', hasNested: true },
  { name: 'footnote', hasNested: true },
  { name: 'marginpar', hasNested: true },
  { name: 'includegraphics', hasNested: true },
  { name: 'centering', hasNested: false },
  { name: 'raggedright', hasNested: false },
  { name: 'raggedleft', hasNested: false },
  { name: 'hfill', hasNested: false },
  { name: 'vfill', hasNested: false },
  { name: 'hspace', hasNested: true },
  { name: 'vspace', hasNested: true },
  { name: 'smallskip', hasNested: false },
  { name: 'medskip', hasNested: false },
  { name: 'bigskip', hasNested: false },
  { name: 'quad', hasNested: false },
  { name: 'qquad', hasNested: false },
  { name: 'item', hasNested: false },
  { name: 'enumerate', hasNested: false },
  { name: 'description', hasNested: false },
  { name: 'figure', hasNested: false },
  { name: 'table', hasNested: false },
  { name: 'caption', hasNested: true },
  { name: 'subfigure', hasNested: false },
  { name: 'minipage', hasNested: true },
  { name: 'parbox', hasNested: true },
  { name: 'fbox', hasNested: true },
  { name: 'framebox', hasNested: true },
  { name: 'rule', hasNested: true },
  { name: 'hrule', hasNested: false },
  { name: 'vrule', hasNested: false },
  { name: 'hline', hasNested: false },
  { name: 'cline', hasNested: true },
  { name: 'multicolumn', hasNested: true },
  { name: 'multirow', hasNested: true },
  { name: 'arraystretch', hasNested: true },
  { name: 'tabcolsep', hasNested: true },
  { name: 'arraycolsep', hasNested: true },
  { name: 'columnwidth', hasNested: false },
  { name: 'textwidth', hasNested: false },
  { name: 'linewidth', hasNested: false },
  { name: 'pagewidth', hasNested: false },
  { name: 'pageheight', hasNested: false },
  { name: 'topmargin', hasNested: false },
  { name: 'bottommargin', hasNested: false },
  { name: 'leftmargin', hasNested: false },
  { name: 'rightmargin', hasNested: false },
  { name: 'pagestyle', hasNested: true },
  { name: 'thispagestyle', hasNested: true },
  { name: 'markboth', hasNested: true },
  { name: 'markright', hasNested: true },
  { name: 'leftmark', hasNested: false },
  { name: 'rightmark', hasNested: false },
  { name: 'appendix', hasNested: false },
  { name: 'bibliography', hasNested: true },
  { name: 'bibliographystyle', hasNested: true },
  { name: 'bibitem', hasNested: true },
  { name: 'newcommand', hasNested: true },
  { name: 'renewcommand', hasNested: true },
  { name: 'newenvironment', hasNested: true },
  { name: 'renewenvironment', hasNested: true },
  { name: 'def', hasNested: true },
  { name: 'let', hasNested: true },
  { name: 'gdef', hasNested: true },
  { name: 'xdef', hasNested: true },
  { name: 'edef', hasNested: true },
  { name: 'providecommand', hasNested: true },
  { name: 'DeclareRobustCommand', hasNested: true },
  { name: 'makeatletter', hasNested: false },
  { name: 'makeatother', hasNested: false },
  { name: 'catcode', hasNested: true },
  { name: 'newcounter', hasNested: true },
  { name: 'setcounter', hasNested: true },
  { name: 'addtocounter', hasNested: true },
  { name: 'stepcounter', hasNested: true },
  { name: 'refstepcounter', hasNested: true },
  { name: 'value', hasNested: true },
  { name: 'arabic', hasNested: true },
  { name: 'roman', hasNested: true },
  { name: 'Roman', hasNested: true },
  { name: 'alph', hasNested: true },
  { name: 'Alph', hasNested: true },
  { name: 'fnsymbol', hasNested: true },
  { name: 'newtheorem', hasNested: true },
  { name: 'theoremstyle', hasNested: true },
  { name: 'proof', hasNested: false },
  { name: 'qed', hasNested: false },
  { name: 'newpage', hasNested: false },
  { name: 'clearpage', hasNested: false },
  { name: 'cleardoublepage', hasNested: false },
]
