export const texKeywords = [
//   "usepackage", 
//   "begin",
//   "end",
//   "itemize", (DUPLICATE - SHOULD BE A ENVIRONMENT VARIABLE)
//   "graphicspath",
//   "documentclass",
//   "section",
//   "subsection",
//   "subsubsection",
//   "chapter",
//   "part",
//   "title",
//   "author",
//   "date",
  "maketitle",
  "tableofcontents",
  "newpage",
  "clearpage",
  "pagebreak",
  "newline",
  "linebreak",
  "noindent",
  "indent",
  "textbf",
  "textit",
  "textsc",
  "texttt",
  "emph",
  "underline",
  "cite",
  "ref",
  "label",
  "footnote",
  "marginpar",
  "includegraphics",
  "centering",
  "raggedright",
  "raggedleft",
  "hfill",
  "vfill",
  "hspace",
  "vspace",
  "smallskip",
  "medskip",
  "bigskip",
  "quad",
  "qquad",
  "item",
  "enumerate",
  "description",
  "figure",
  "table",
  "caption",
  "subfigure",
  "minipage",
  "parbox",
  "fbox",
  "framebox",
  "rule",
  "hrule",
  "vrule",
  "hline",
  "cline",
  "multicolumn",
  "multirow",
  "arraystretch",
  "tabcolsep",
  "arraycolsep",
  "columnwidth",
  "textwidth",
  "linewidth",
  "pagewidth",
  "pageheight",
  "topmargin",
  "bottommargin",
  "leftmargin",
  "rightmargin",
  "pagestyle",
  "thispagestyle",
  "markboth",
  "markright",
  "leftmark",
  "rightmark",
  "appendix",
  "bibliography",
  "bibliographystyle",
  "bibitem",
  "newcommand",
  "renewcommand",
  "newenvironment",
  "renewenvironment",
  "def",
  "let",
  "gdef",
  "xdef",
  "edef",
  "providecommand",
  "DeclareRobustCommand",
  "makeatletter",
  "makeatother",
  "catcode",
  "newcounter",
  "setcounter",
  "addtocounter",
  "stepcounter",
  "refstepcounter",
  "value",
  "arabic",
  "roman",
  "Roman",
  "alph",
  "Alph",
  "fnsymbol",
  "newtheorem",
  "theoremstyle",
  "proof",
  "qed",
  "newpage",
  "clearpage",
  "cleardoublepage"
];

export const texEnvironments = [
  "document",
  "abstract",
  "itemize",
  "enumerate",
  "description",
  "figure",
  "table",
  "equation",
  "align",
  "alignat",
  "gather",
  "multline",
  "split",
  "cases",
  "matrix",
  "pmatrix",
  "bmatrix",
  "vmatrix",
  "Vmatrix",
  "array",
  "tabular",
  "tabbing",
  "verbatim",
  "verse",
  "quotation",
  "quote",
  "center",
  "flushleft",
  "flushright",
  "minipage",
  "theorem",
  "lemma",
  "corollary",
  "proposition",
  "definition",
  "example",
  "remark",
  "proof",
  "thebibliography",
  "titlepage",
  "appendix"
];

export const texPackages = [
  "amsmath",
  "amsfonts",
  "amssymb",
  "graphicx",
  "hyperref",
  "url",
  "xcolor",
  "color",
  "tikz",
  "pgfplots",
  "booktabs",
  "array",
  "longtable",
  "multirow",
  "makecell",
  "geometry",
  "fancyhdr",
  "babel",
  "inputenc",
  "fontenc",
  "lmodern",
  "microtype",
  "setspace",
  "enumitem",
  "listings",
  "algorithm2e",
  "algorithmic",
  "subfig",
  "subcaption",
  "float",
  "wrapfig",
  "caption",
  "natbib",
  "biblatex",
  "csquotes",
  "appendix",
  "tocbibind",
  "nomencl",
  "glossaries",
  "acronym",
  "siunitx",
  "textcomp",
  "gensymb",
  "mhchem",
  "chemfig",
  "pgf",
  "pgffor",
  "calc",
  "xparse",
  "etoolbox",
  "xstring",
  "ifthen",
  "forloop"
];

export interface TexKeyword {
  name: string;
  hasNested?: boolean;
  nestedOptions?: string[];
}

export const texKeywords: TexKeyword[] = [
  {
    name: "usepackage",
    hasNested: true,
    nestedOptions: texPackages
  },
 {
    name: "begin",
    hasNested: true,
    nestedOptions: texEnvironments
  },
  {
    name: "end",
    hasNested: true,
    nestedOptions: texEnvironments
  },
  {
    name: "documentclass",
    hasNested: true,
    nestedOptions: ["article", "report", "book", "letter"]
  },
    // TODO: Is it possible to insert an array of uploaded files in filament?   
    {
    name: "graphicspath",
    hasNested: true,
    nestedOptions: []
  },
  {
    name: "documentclass",
    hasNested: true,
    nestedOptions: ["article", "report", "book", "letter"]
  },
  {
    name: "section",
    hasNested: false,
  },
  {
    name: "subsection",
    hasNested: false,
  },
    {
    name: "subsubsection",
    hasNested: false,
  },
 {
    name: "chapter",
    hasNested:false,
  },
  {
    name: "part",
    hasNested: false,
  },
  {
    name: "title",
    hasNested: false,
  },
    {
    name: "author",
    hasNested: false,
  },
 {
    name: "date",
    hasNested: false,
  },
  {
    name: "maketitle",
    hasNested: false,
  },
//   {
//     name: "documentclass",
//     hasNested: true,
//     nestedOptions: ["article", "report", "book", "letter"]
//   },
//     {
//     name: "usepackage",
//     hasNested: true,
//     nestedOptions: texPackages
//   },
//  {
//     name: "begin",
//     hasNested: true,
//     nestedOptions: texEnvironments
//   },
//   {
//     name: "end",
//     hasNested: true,
//     nestedOptions: texEnvironments
//   },
//   {
//     name: "documentclass",
//     hasNested: true,
//     nestedOptions: ["article", "report", "book", "letter"]
//   },
//   {
//     name: "section"
//   }
];
